name: DD Bun CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: oven-sh/setup-bun@v2
    - uses: actions/checkout@v4
    - run: bun i
    - run: bun run format:check

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: oven-sh/setup-bun@v2
    - uses: actions/checkout@v4
    - run: bun i
    - run: bun run lint:check

  type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: oven-sh/setup-bun@v2
    - uses: actions/checkout@v4
    - run: bun i
    - run: bun run type:check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: oven-sh/setup-bun@v2
    - uses: actions/checkout@v4
    - run: bun i
    - run: bun run all:test

  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: oven-sh/setup-bun@v2
    - uses: actions/checkout@v4
    - run: bun i
    - run: bun run client:build
